In [30]:
import numpy as np

n = np.arange(9)
a = n.reshape((3,3,1))
a

b = ((np.arange(5))*10).reshape((1,1,-1))
c = a+b
print(c.shape)
print(c[:,:,0])
d = c.reshape((3,15),order='F')
print(d)

(3, 3, 5)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2 10 11 12 20 21 22 30 31 32 40 41 42]
 [ 3  4  5 13 14 15 23 24 25 33 34 35 43 44 45]
 [ 6  7  8 16 17 18 26 27 28 36 37 38 46 47 48]]
